Update devops_merge_restrictions2.yml

diff --git a/.github/workflows/devops_merge_restrictions2.yml b/.github/workflows/devops_merge_restrictions2.yml
--- a/.github/workflows/devops_merge_restrictions2.yml
+++ b/.github/workflows/devops_merge_restrictions2.yml
@@ -1,21 +1,20 @@
- name: Restrict Merge to DevOps 2
- on:
-   pull_request:
-     branches:
-       - main
- jobs:
-   check-devops:
-     runs-on: ubuntu-latest
-     steps:
-       - name: Check DevOps team
-         env:
-           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-         run: |
-           
-           TEAM_MEMBERS=$(curl -H "Authorization: token $GITHUB_TOKEN" \
-           https://api.github.com/orgs/DevOps/teams/devops/members)
-           echo "Team Members: $TEAM_MEMBERS"
-           if [[ ! " $TEAM_MEMBERS " =~ " ${{ github.actor }} " ]]; then
-             echo "Error: Only DevOps team members can merge to main"
-             exit 1
-           fi
+name: Restrict Merge to DevOps 2
+on:
+  pull_request:
+    branches:
+      - main
+jobs:
+  check-devops:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check DevOps team
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the PAT instead of the default token
+        run: |
+          TEAM_MEMBERS=$(curl -H "Authorization: token $GITHUB_TOKEN" \
+          https://api.github.com/orgs/<organization-name>/teams/<team-name>/members)
+          echo "Team Members: $TEAM_MEMBERS"
+          if [[ ! " $TEAM_MEMBERS " =~ " ${{ github.actor }} " ]]; then
+            echo "Error: Only DevOps team members can merge to main"
+            exit 1
+          fi
